"""Add default to user.role-2

Revision ID: ba5feff01253
Revises: 7da91fab3469
Create Date: 2025-08-09 05:28:02.810638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5feff01253'
down_revision: Union[str, Sequence[str], None] = '7da91fab3469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


    
def upgrade():
    op.alter_column(
        'user', 'role',
        existing_type=sa.String(),
        server_default=sa.text("'user'"),
        existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie', 'imdb_rate',
               existing_type=sa.Float(precision=2, asdecimal=1),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
